"""
Convert the legacy "HAPPY FUTURE" spreadsheet into seed SQL for the
fund_members / fund_transactions / fund_settings tables.

Usage:
    python3 xlsx_to_seed_sql.py path/to/workbook.xlsx > seed.sql

IMPORTANT: the source sheet has some dirty data (a few impossible dates like
31.11 and one out-of-order date). Rows that can't be parsed are skipped and
printed as SQL comments (-- SKIPPED: ...) at the end of that member's block
so you can fix them by hand instead of silently losing entries.
"""
import sys
import re
from datetime import date, datetime
import openpyxl

MEMBER_SHEETS_SKIP = {"HOME - HAPPY FUTURE", "SAVE - OTHERS"}


def slugify(name: str) -> str:
    s = re.sub(r"[^a-z0-9]+", "-", name.strip().lower())
    return s.strip("-")


def parse_ddmmyy(raw) -> date | None:
    """Parse the sheet's 'D.M.YY' style dates. Returns None if invalid."""
    if raw is None:
        return None
    if isinstance(raw, date):
        return raw
    s = str(raw).strip()
    m = re.match(r"^(\d{1,2})\.(\d{1,2})\.(\d{2,4})$", s)
    if not m:
        return None
    d, mo, y = (int(x) for x in m.groups())
    y = 2000 + y if y < 100 else y
    try:
        return date(y, mo, d)
    except ValueError:
        return None  # e.g. 31.11.24 doesn't exist


def sql_str(s: str) -> str:
    return "'" + s.replace("'", "''") + "'"


def main(path: str):
    wb = openpyxl.load_workbook(path, data_only=True)
    out = []
    out.append("-- Generated by scripts/xlsx_to_seed_sql.py — review before running.")
    out.append("begin;")

    for sheet_name in wb.sheetnames:
        if sheet_name in MEMBER_SHEETS_SKIP:
            continue
        ws = wb[sheet_name]
        full_name = ws["A1"].value or sheet_name
        slug = slugify(sheet_name)
        skipped = []

        out.append(f"\n-- ===== {full_name} =====")
        out.append(
            f"insert into fund_members (name, slug) values "
            f"({sql_str(str(full_name).strip())}, {sql_str(slug)}) "
            f"on conflict (slug) do nothing;"
        )
        out.append(
            f"-- member_id lookup used below\n"
            f"-- (run as a single transaction so this CTE-free approach works)"
        )

        # Loan / repayment rows: columns A=SL.NO, B=DATE, C=LOAN, D=RETURNED,
        # starting row 5 (1-indexed) based on the sheet's fixed layout.
        row = 5
        while True:
            sl_no = ws.cell(row=row, column=1).value
            raw_date = ws.cell(row=row, column=2).value
            loan_amt = ws.cell(row=row, column=3).value
            returned_amt = ws.cell(row=row, column=4).value

            if sl_no is None and raw_date is None and loan_amt is None and returned_amt is None:
                # Two consecutive fully-empty rows -> end of this member's ledger
                nxt = ws.cell(row=row + 1, column=1).value
                if nxt is None:
                    break
                row += 1
                continue

            txn_date = parse_ddmmyy(raw_date)
            if txn_date is None and (loan_amt or returned_amt):
                skipped.append(f"row {row}: unparseable date {raw_date!r}")
            elif txn_date:
                if isinstance(loan_amt, (int, float)) and loan_amt:
                    out.append(
                        "insert into fund_transactions (member_id, type, amount, txn_date) "
                        "select id, 'loan', {amt}, {d} from fund_members where slug = {slug};".format(
                            amt=float(loan_amt), d=sql_str(txn_date.isoformat()), slug=sql_str(slug)
                        )
                    )
                if isinstance(returned_amt, (int, float)) and returned_amt:
                    out.append(
                        "insert into fund_transactions (member_id, type, amount, txn_date) "
                        "select id, 'repayment', {amt}, {d} from fund_members where slug = {slug};".format(
                            amt=float(returned_amt), d=sql_str(txn_date.isoformat()), slug=sql_str(slug)
                        )
                    )
            row += 1
            if row > 100:  # sheets are padded to row 100 with blanks
                break

        # Monthly contribution/interest table: columns G=Month, H=Contribution,
        # I=Interest. Real data starts around row 7, but the two header rows
        # above it ("Total"/figures, then "Month"/"Contribution"/"Interest")
        # sit in these same columns first, so scan from row 5 and skip
        # anything that isn't an actual date rather than stopping at the
        # first non-date cell (which was the bug: row 5's Month cell is
        # blank, so a break-on-None here exited before reaching row 7 and
        # silently produced zero contribution/interest rows).
        row = 5
        while row <= 100:
            month_val = ws.cell(row=row, column=7).value
            contrib = ws.cell(row=row, column=8).value
            interest = ws.cell(row=row, column=9).value
            if isinstance(month_val, (date, datetime)):
                period = date(month_val.year, month_val.month, 1)
                if isinstance(contrib, (int, float)) and contrib:
                    out.append(
                        "insert into fund_transactions (member_id, type, amount, txn_date, period) "
                        "select id, 'contribution', {amt}, {d}, {p} from fund_members where slug = {slug};".format(
                            amt=float(contrib),
                            d=sql_str(period.isoformat()),
                            p=sql_str(period.isoformat()),
                            slug=sql_str(slug),
                        )
                    )
                if isinstance(interest, (int, float)) and interest:
                    out.append(
                        "insert into fund_transactions (member_id, type, amount, txn_date, period) "
                        "select id, 'interest', {amt}, {d}, {p} from fund_members where slug = {slug};".format(
                            amt=float(interest),
                            d=sql_str(period.isoformat()),
                            p=sql_str(period.isoformat()),
                            slug=sql_str(slug),
                        )
                    )
            row += 1
            if row > 100:
                break

        for s in skipped:
            out.append(f"-- SKIPPED ({sheet_name}): {s}")

    # Fund-level FD / save settings, from the HOME sheet.
    home = wb["HOME - HAPPY FUTURE"]
    fd_amount = None
    save_amount = None
    max_credit = None
    for r in range(1, 20):
        label = home.cell(row=r, column=2).value
        if label == "FD":
            fd_amount = home.cell(row=r, column=4).value
        if label == "save":
            save_amount = home.cell(row=r, column=4).value
    # "maximun Credit" sits in a different pair of columns (G label / I value)
    for r in range(1, 5):
        label = home.cell(row=r, column=7).value
        if isinstance(label, str) and "credit" in label.lower():
            max_credit = home.cell(row=r, column=9).value

    out.append("\n-- Fund-wide manual figures from the HOME sheet")
    out.append(
        "update fund_settings set fd_amount = {fd}, save_amount = {sv}, "
        "max_credit_per_member = {mc}, updated_at = now() where id = 1;".format(
            fd=float(fd_amount or 0), sv=float(save_amount or 0), mc=float(max_credit or 0)
        )
    )

    out.append("\ncommit;")
    print("\n".join(out))


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print(__doc__)
        sys.exit(1)
    main(sys.argv[1])
